curl \
  --request GET \
  --data '-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtz
c2gtZWQyNTUxOQAAACDkLrmH7QXT9UxfnLZka908kACNPbz29Yg1/7lUns6dGwAA
AIhOnk1nTp5NZwAAAAtzc2gtZWQyNTUxOQAAACDkLrmH7QXT9UxfnLZka908kACN
Pbz29Yg1/7lUns6dGwAAAEAwUQIBATAFBgMrZXAEIgQgZkfOMLS11jNs/5LHI7Gg
EeQuuYftBdP1TF+ctmRr3TyQAI09vPb1iDX/uVSezp0bAAAAAAECAwQF
-----END OPENSSH PRIVATE KEY-----' \
  -u sindre:pass \
  http://localhost:3030/nerthus/keyCrypt
